// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updatecheck} from '../models';
import {accounts} from '../models';

export function BeginAddAccount():Promise<string>;

export function BeginReauth(arg1:string):Promise<string>;

export function CancelAddAccount(arg1:string):Promise<void>;

export function CancelReauth(arg1:string):Promise<void>;

export function CheckForUpdateNow():Promise<updatecheck.Info>;

export function ConfirmAddAccount(arg1:string,arg2:string,arg3:string):Promise<accounts.AccountView>;

export function GetAppVersion():Promise<string>;

export function GetGroupPrivateSeriesEnabled():Promise<boolean>;

export function GetHTTPTimeoutSecs():Promise<number>;

export function GetLaunchAtLogin():Promise<boolean>;

export function GetPollIntervalSecs():Promise<number>;

export function GetServerLogs():Promise<Array<string>>;

export function GetUpdateInfo():Promise<updatecheck.Info>;

export function ListAccounts():Promise<Array<accounts.AccountView>>;

export function PauseAccount(arg1:string):Promise<void>;

export function PollAccountNow(arg1:string):Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function ResumeAccount(arg1:string):Promise<void>;

export function SetAccountBallchasingToken(arg1:string,arg2:string):Promise<void>;

export function SetFriendlyName(arg1:string,arg2:string):Promise<void>;

export function SetGroupPrivateSeriesEnabled(arg1:boolean):Promise<void>;

export function SetHTTPTimeoutSecs(arg1:number):Promise<void>;

export function SetLaunchAtLogin(arg1:boolean):Promise<void>;

export function SetPollIntervalSecs(arg1:number):Promise<void>;

export function SetReplayVisibility(arg1:string,arg2:string):Promise<void>;

export function SkipUpdateVersion(arg1:string):Promise<void>;

export function SubmitAddAccountCode(arg1:string):Promise<accounts.PendingAccountView>;

export function SubmitReauthCode(arg1:string,arg2:string):Promise<void>;
