// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginAddAccount() {
  return window['go']['main']['App']['BeginAddAccount']();
}

export function BeginReauth(arg1) {
  return window['go']['main']['App']['BeginReauth'](arg1);
}

export function CancelAddAccount(arg1) {
  return window['go']['main']['App']['CancelAddAccount'](arg1);
}

export function CancelReauth(arg1) {
  return window['go']['main']['App']['CancelReauth'](arg1);
}

export function CheckForUpdateNow() {
  return window['go']['main']['App']['CheckForUpdateNow']();
}

export function ConfirmAddAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfirmAddAccount'](arg1, arg2, arg3);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetFailedUploadsMaxCount() {
  return window['go']['main']['App']['GetFailedUploadsMaxCount']();
}

export function GetFailedUploadsRetryHour() {
  return window['go']['main']['App']['GetFailedUploadsRetryHour']();
}

export function GetGroupPrivateSeriesEnabled() {
  return window['go']['main']['App']['GetGroupPrivateSeriesEnabled']();
}

export function GetHTTPTimeoutSecs() {
  return window['go']['main']['App']['GetHTTPTimeoutSecs']();
}

export function GetLaunchAtLogin() {
  return window['go']['main']['App']['GetLaunchAtLogin']();
}

export function GetPollIntervalSecs() {
  return window['go']['main']['App']['GetPollIntervalSecs']();
}

export function GetServerLogs() {
  return window['go']['main']['App']['GetServerLogs']();
}

export function GetUpdateInfo() {
  return window['go']['main']['App']['GetUpdateInfo']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function PauseAccount(arg1) {
  return window['go']['main']['App']['PauseAccount'](arg1);
}

export function PollAccountNow(arg1) {
  return window['go']['main']['App']['PollAccountNow'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function ResumeAccount(arg1) {
  return window['go']['main']['App']['ResumeAccount'](arg1);
}

export function RetryFailedUploadsNow() {
  return window['go']['main']['App']['RetryFailedUploadsNow']();
}

export function SetAccountBallchasingToken(arg1, arg2) {
  return window['go']['main']['App']['SetAccountBallchasingToken'](arg1, arg2);
}

export function SetFailedUploadsMaxCount(arg1) {
  return window['go']['main']['App']['SetFailedUploadsMaxCount'](arg1);
}

export function SetFailedUploadsRetryHour(arg1) {
  return window['go']['main']['App']['SetFailedUploadsRetryHour'](arg1);
}

export function SetFriendlyName(arg1, arg2) {
  return window['go']['main']['App']['SetFriendlyName'](arg1, arg2);
}

export function SetGroupPrivateSeriesEnabled(arg1) {
  return window['go']['main']['App']['SetGroupPrivateSeriesEnabled'](arg1);
}

export function SetHTTPTimeoutSecs(arg1) {
  return window['go']['main']['App']['SetHTTPTimeoutSecs'](arg1);
}

export function SetLaunchAtLogin(arg1) {
  return window['go']['main']['App']['SetLaunchAtLogin'](arg1);
}

export function SetPollIntervalSecs(arg1) {
  return window['go']['main']['App']['SetPollIntervalSecs'](arg1);
}

export function SetReplayVisibility(arg1, arg2) {
  return window['go']['main']['App']['SetReplayVisibility'](arg1, arg2);
}

export function SkipUpdateVersion(arg1) {
  return window['go']['main']['App']['SkipUpdateVersion'](arg1);
}

export function SubmitAddAccountCode(arg1) {
  return window['go']['main']['App']['SubmitAddAccountCode'](arg1);
}

export function SubmitReauthCode(arg1, arg2) {
  return window['go']['main']['App']['SubmitReauthCode'](arg1, arg2);
}
