// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginAddAccount() {
  return window['go']['main']['App']['BeginAddAccount']();
}

export function BeginReauth(arg1) {
  return window['go']['main']['App']['BeginReauth'](arg1);
}

export function CancelAddAccount(arg1) {
  return window['go']['main']['App']['CancelAddAccount'](arg1);
}

export function CancelReauth(arg1) {
  return window['go']['main']['App']['CancelReauth'](arg1);
}

export function ConfirmAddAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfirmAddAccount'](arg1, arg2, arg3);
}

export function GetHTTPTimeoutSecs() {
  return window['go']['main']['App']['GetHTTPTimeoutSecs']();
}

export function GetLaunchAtLogin() {
  return window['go']['main']['App']['GetLaunchAtLogin']();
}

export function GetPollIntervalSecs() {
  return window['go']['main']['App']['GetPollIntervalSecs']();
}

export function GetServerLogs() {
  return window['go']['main']['App']['GetServerLogs']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function PauseAccount(arg1) {
  return window['go']['main']['App']['PauseAccount'](arg1);
}

export function PollAccountNow(arg1) {
  return window['go']['main']['App']['PollAccountNow'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function ResumeAccount(arg1) {
  return window['go']['main']['App']['ResumeAccount'](arg1);
}

export function SetAccountBallchasingToken(arg1, arg2) {
  return window['go']['main']['App']['SetAccountBallchasingToken'](arg1, arg2);
}

export function SetFriendlyName(arg1, arg2) {
  return window['go']['main']['App']['SetFriendlyName'](arg1, arg2);
}

export function SetHTTPTimeoutSecs(arg1) {
  return window['go']['main']['App']['SetHTTPTimeoutSecs'](arg1);
}

export function SetLaunchAtLogin(arg1) {
  return window['go']['main']['App']['SetLaunchAtLogin'](arg1);
}

export function SetPollIntervalSecs(arg1) {
  return window['go']['main']['App']['SetPollIntervalSecs'](arg1);
}

export function SubmitAddAccountCode(arg1) {
  return window['go']['main']['App']['SubmitAddAccountCode'](arg1);
}

export function SubmitReauthCode(arg1, arg2) {
  return window['go']['main']['App']['SubmitReauthCode'](arg1, arg2);
}
